Feature/export (#22)
* Add in FORCE_COLOR env variable override

* add export option + force colour env variable

* add check of test pypi to pipeline

* lint fix

* add dependencies to check job

* more workflow changes

* bump version to 0.6.0

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -11,6 +11,114 @@ permissions:
   checks: write
 
 jobs:
+
+  checkpypi:
+    if: github.event_name == 'pull_request' ## only check test PyPi on pull request - main locked down
+    needs: 
+      - test
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        python-version: ["3.11"]
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v4
+        with:
+          python-version: ${{ matrix.python-version }}
+
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -e .
+          pip install -r requirements-dev.txt
+      
+      - name: Check Project Version
+        run: |
+          VERSION=$(cat pyproject.toml | tomlq -r .project.version)
+          TEST_VERSIONS=$(curl "https://test.pypi.org/pypi/cfncli/json" | jq -rc '.releases | keys')
+          if echo "$TEST_VERSIONS" | jq -e --arg version "$VERSION" 'index($version)' > /dev/null; then
+            echo "Error: Version $VERSION already exists in test.pypi.org"
+            exit 1
+          fi
+          echo "Version $VERSION is available for publishing"
+
+  publish-to-testpypi:
+    name: Publish to TestPyPI
+    needs:
+      - test
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        python-version: ["3.11"]
+    if: github.ref == 'refs/heads/main' # run if push to main
+
+    environment:
+      name: testpypi
+      url: https://test.pypi.org/project/cfncli
+
+    permissions:
+      id-token: write  # IMPORTANT: mandatory for trusted publishing
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v4
+        with:
+          python-version: ${{ matrix.python-version }}
+
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -e .
+          pip install -r requirements-dev.txt
+
+      - name: Build package
+        run: |
+          make build
+
+      - name: Publish distribution 📦 to TestPyPI
+        uses: pypa/gh-action-pypi-publish@release/v1
+        with:
+          repository-url: https://test.pypi.org/legacy/
+
+  publish-to-pypi:
+    name: Publish to PyPI
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        python-version: ["3.11"]
+    if: startsWith(github.ref, 'refs/tags/v')
+    
+    environment:
+      name: pypi
+      url: https://pypi.org/project/cfncli
+    
+    permissions:
+      id-token: write
+    
+    steps:
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v4
+        with:
+          python-version: ${{ matrix.python-version }}
+          
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+
+      - name: Download from TestPyPI and republish to PyPI
+        run: |
+          TAG_VERSION=${GITHUB_REF#refs/tags/v}
+          pip download --index-url https://test.pypi.org/simple/ --no-deps cfncli==$TAG_VERSION
+          
+      - name: Publish to PyPI
+        uses: pypa/gh-action-pypi-publish@release/v1
+        with:
+          packages-dir: ./
+
   test:
     runs-on: ubuntu-latest
     strategy:
@@ -38,7 +146,7 @@ jobs:
     - name: Run tests
       run: |
         pytest --junitxml=junit.xml --cov=cfncli --cov-report=xml --cov-report=html --cov-report=term
-    
+
     - name: Upload test results
       uses: actions/upload-artifact@v4
       if: always()
